version: "3.1"
services:

  jupyter-lab:
    build: jupyter-lab
    container_name: jupyter-lab
    restart: unless-stopped
    user: root
    env_file:
      ../.env
    ports:
     - "47755:8000"
    volumes:
      - ../scripts:/home:rw
      - ../jupyter.py:/conf/jupyter.py
      - ./crontab/crontabs/:/var/spool/cron/crontabs/:rw

  jupyter-cron:
    build: jupyter-cron 
    restart: unless-stopped
    container_name: jupyter-cron
    env_file:
      ../.env    
    volumes:
      - ../scripts:/home/jovyan:rw
      - ../jupyter.py:/conf/jupyter.py
      - ./crontab/crontabs/:/var/spool/cron/crontabs/
